services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    working_dir: /app/
    command: "npm run dev"

  db:
    image: couchdb:3
    environment:
      COUCHDB_PASSWORD: 'password'
      COUCHDB_USER: 'admin'
    ports:
      - "5984:5984"
