services:
  app:
    image: node:18
    volumes:
      - ./:/app/
    working_dir: /app/

  db:
    image: couchdb:3
    environment:
      COUCHDB_PASSWORD: 'password'
      COUCHDB_USER: 'admin'
    ports:
      - "5984:5984"
